//POKEMON TYPES

export const POKETYPE = 'POKETYPE';


//POKEMON TEAM

export const ADD_TO_TEAM = 'ADD_TO_TEAM';
export const REMOVE_FROM_TEAM = 'REMOVE_FROM_TEAM'
export const CLEAR_TEAM = 'CLEAR_TEAM';